name: Deploy to Minikube using GitHub Actions

on: [push]
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
      with:
        cpus: 2
        memory: 4000
        driver: docker

    - name: Try the cluster
      run: kubectl get pods -A
      
    - name: Build image
      run: |
          eval $(minikube -p minikube docker-env)
          docker build -t devopshint/node-app:latest .
          
    - name: Deploy to minikube
      run: kubectl apply -f k8s-node-app.yaml
      
    - name: Wait for pods
      run: |
        sleep 30
        kubectl get pods -o wide
        
    - name: Check pod status
      run: |
        kubectl describe pod -l app=nodejs-app
        kubectl logs -l app=nodejs-app
        
    - name: Test service
      run: |
        minikube service list
        sleep 10
        SERVICE_URL=$(minikube service nodejs-app --url)
        echo "Service URL: $SERVICE_URL"
        curl $SERVICE_URL
