name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image and deploy to minikube
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Updated to v4
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Build image
      run: |
        eval $(minikube -p minikube docker-env)
        docker build -t devopshint/node-app:latest .
        echo "verifying images:"
        docker images
    - name: Deploy to minikube
      run: kubectl apply -f k8s-node-app.yaml # Corrected syntax
    - name: Verify deployment
      run: kubectl get all
    - name: Test service URLs
      run: |
        minikube service list
        minikube service nodejs-app --url
